
server:
    port: 8874

spring:
    datasource:
        primary:
            url: jdbc:mysql://10.8.0.1:3306/test001?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
        secondary:
            url:  jdbc:mysql://10.8.0.1:3306/test002?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
        druid:
            max-wait: 10000 #获取连接时最大等待时间，单位毫秒
            initial-size: 10 #初始化时建立物理连接的个数
            max-active: 100 #最大连接池数量
            min-idle: 10 #最小连接数
            time-between-eviction-runs-millis: 3600000 #检测连接的间隔时间
            min-evictable-idle-time-millis: 300000 #连接的最小生存时间
            test-while-idle: true  #检测连接是否有效
            test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            validation-query: SELECT 1 #用来检测连接是否有效的sql
            filters: stat #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
            stat-view-servlet:
                url-pattern: /druid/*
                reset-enable: true #允许清空统计数据
                login-username: root #监控后台管理账号和密码
                login-password: root
            web-stat-filter:
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    jpa:
        database: mysql
        generate-ddl: true
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true